baseurl = "/"
title = "„ÄåÂ∫îÂèØÈíß„ÄçKejun Albert Ying"
theme = "typography"

ignoreFiles = ["\\.qmd$", "\\.ipynb$", "\\.Rmd$", "\\.Rmarkdown$", "_cache$", "index\\.html", "about\\.html", "static/blog/\\*_files/", "README.md", ".venv"]

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Sitemap configuration for SEO
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Minification for performance
[minify]
  minifyOutput = true

[params]
    introtag = "introduction"

    intro = "Hello! I'm a postdoctoral fellow at [Stanford University](https://med.stanford.edu/) in [Tony Wyss-Coray's lab](https://wyss-coray.stanford.edu/) and [University of Washington](https://www.washington.edu/) in [David Baker's lab](https://www.bakerlab.org/), supported by an NIH/NIA F99K00 fellowship. I earned my Ph.D. in Biological Sciences from [Harvard Medical School](https://hms.harvard.edu/) (2025) in [Vadim Gladyshev's lab](https://gladyshevlab.bwh.harvard.edu/) and an M.Sc. in Computational Science and Engineering from [Harvard SEAS](https://seas.harvard.edu/) (2024). My research merges aging biology with **protein design** to tackle neurodegeneration, focusing on the causes of aging, epigenetics, metabolism, and multi-omics. I'm building the next generation of therapeutics through **machine learning** and **protein design**. " 

    favicon = "avatar.png"
    highlightstyle  = "foundation"

    iconsource = "simple-icons"

    description = "Kejun (Albert) Ying's personal website | Â∫îÂèØÈíßÁöÑ‰∏™‰∫∫ÁΩëÁ´ô"
    keywords = "personal, science, aging"

    customcss = ["custom_style.css"]

    umami       = true
    umamilink   = "https://kejunying.com/share/script.js"
    umamiid     = "ce4b7b41-6d20-47f0-81b2-e316006cc9f2"
    umamitag = "kejunying"

# recent news
    [[params.news]]
        date = "2025-12"
        name = "My alumni profile is featured on Harvard SEAS News!"
        url = "https://seas.harvard.edu/news/2025/12/alumni-profile-kejun-ying-sm-24-phd-25"
    [[params.news]]
        date = "2025-12"
        name = "ClockBase Agent is featured on MIT Technology Review China!"
        url = "https://www.mittrchina.com/news/detail/15539"
    [[params.news]]
        date = "2025-11"
        name = "ClockBase Agent preprint is out! We developed AI agents that autonomously discover aging interventions from millions of molecular profiles, identifying 500+ compounds that reduce biological age."
        url = "https://www.biorxiv.org/content/10.1101/2023.02.28.530532v4"
    [[params.news]]
        date = "2025-11"
        name = "Our new paper in Nature Aging is published! With the Biomarkers of Aging Consortium, we present Biolearn, an open-source framework unifying 39 aging biomarkers across 20,000+ individuals from multiple cohorts."
        url = "https://nature.com/articles/s43587-025-00987-y"
    [[params.news]]
        date = "2025-01"
        name = "Excited to join Tony Wyss-Coray lab at Stanford University & Baker lab at Institute for Protein Design, University of Washington as F99K00 Postdoc fellow! Merging aging biology + protein design to tackle neurodegeneration. üß¨"
        url = ""
    [[params.news]]
        date = "2025-03"
        name = "Officially Dr. Ying! I successfully defended my Ph.D. at Harvard."
        url = "https://youtu.be/Tm7AtwLywEg?si=OdXa_ALebc1OsXSe"
    [[params.news]]
        date = "2025-03"
        name = "We are featured as semifinalist of Harvard President's Innovation Challenge, Health Care and Life Sciences Track."
        url = "https://www.harvard.edu/news/2025/03/2025-hpc-semifinalists-announced"
    [[params.news]]
        date = "2025-01"
        name = "MethylGPT is featured in Eric Topol's opinion piece in Science Magazine!"
        url = "https://www.science.org/doi/10.1126/science.adv4414"
    [[params.news]]
        date = "2025-01"
        name = "I co-founded Avinasi Labs, a platform fostering collaboration and data sharing to overcome fragmented data and funding barriers in longevity science."
        url = "https://www.avinasi.com/"

    [[params.news]]
        date = "2024-12"
        name = "My interview with Brenda at A4LI is online!"
        url = "https://a4li.org/scientist-spotlight-ep-14-albert-ying/"
    [[params.news]]
        date = "2024-11"
        name = "We released the one of the first foundation models for the DNA methylome -- MethylGPT."
        url = "https://www.biorxiv.org/content/10.1101/2024.10.30.621013v2"
    [[params.news]]
        date = "2024-10"
        name = "My perpective on causal inference in epigenetic aging is published in *Nature Reviews Genetics*!"
        url = "https://www.nature.com/articles/s41576-024-00799-7"
    [[params.news]]
        date = "2024-10"
        name = "My paper on centenarian LoF mutations is published in *Nature Communications*!"
        url = "https://www.nature.com/articles/s41467-024-52967-2"
    [[params.news]]
        date = "2024-10"
        name = "Congratulations to my postdoc co-mentor, David Baker, for winning the 2024 **Nobel Prize in Chemistry**!"
        url = "https://www.nobelprize.org/prizes/chemistry/2024/press-release/"
    [[params.news]]
        date = "2024-02"
        name = "I received a *perfect* **Impact Score of 10** in the NIA **F99/K00** application!"
        url = "https://x.com/KejunYing/status/1756086454709600378?s=20"
    [[params.news]]
        date = "2024-02"
        name = "Our paper on the causal role of DNA methylation in aging featured on the cover of Nature Aging."
        url = "https://www.nature.com/nataging/volumes/4/issues/2"
    [[params.news]]
        date = "2023-12"
        name = "I received the best poster award on Inaugural Biomarker of Aging Symposium."
        url = "https://x.com/KejunYing/status/1732771615824638318?s=20"
        
    
    # Social links
    [[params.social]]
        name = "GitHub"
        icon = "github"
        weight = 1
        url = "https://github.com/albert-ying/"
    [[params.social]]
        name = "LinkedIn"
        icon = "inspire"
        weight = 2
        url = "https://www.linkedin.com/in/kejun-albert-ying/"
    [[params.social]]
        name = "Twitter"
        icon = "x"
        weight = 4
        url = "https://twitter.com/kejunying/"
    [[params.social]]
        name = "ORCID"
        icon = "orcid"
        weight = 5
        url = "https://orcid.org/0000-0002-1791-6176"
    [[params.social]]
        name = "Google Scholar"
        icon = "googlescholar"
        weight = 6
        url = "https://scholar.google.com/citations?user=JS7AdkcAAAAJ&hl=en"
    [[params.social]]
        name = "Mail"
        icon = "gmail"
        weight = 7
        url = "mailto:kying@g.harvard.edu"

# Menu links
[menu]
    [[menu.main]]
        name = "Home"
        url  = "/"
        weight = 1
    [[menu.main]]
        name = "Talks"
        url  = "/talks"
        weight = 2
    [[menu.main]]
        name = "Research"
        url = "/research"
        weight = 4
    [[menu.main]]
        name = "Cv"
        url = "/cv"
        weight = 5
    [[menu.main]]
        name = "Contact"
        url = "/about"
        weight = 6
    [[menu.main]]
        name = "Poetry"
        url = "/poetry"    
        weight = 7
